In [1]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('cereals.csv')

In [3]:
df.head(5)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843

In [4]:
len(df)

77

In [5]:
df.head(17)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.00,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.00,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.00,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.00,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.00,0.75,34.384843
5,Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.00,0.75,29.509541
6,Apple Jacks,K,C,110,2,0,125,1.0,11.0,14,30,25,2,1.00,1.00,33.174094
7,Basic 4,G,C,130,3,2,210,2.0,18.0,8,100,25,3,1.33,0.75,37.038562
8,Bran Chex,R,C,90,2,1,200,4.0,15.0,6,125,25,1,1.00,0.67,49.120253
9,Bran Flakes,P,C,90,3,0,210,5.0,13.0,5,190,25,3,1.00,0.67,53.313813
10,Cap'n'Crunch,Q,C,120,1,2,220,0.0,12.0,12,35,25,2,1.00,0.75,18.042851
11,Cheerios,G,C,110,6,2,290,2.0,17.0,1,105,25,1,1.00,1.25,50.764999
12,Cinnamon Toast Crunch,G,C,120,1,3,210,0.0,13.0,9,45,25,2,1.00,0.75,19.823573
13,Clusters,G,C,110,3,2,140,2.0,13.0,7,105,25,3,1.00,0.50,40.400208
14,Cocoa Puffs,G,C,110,1,1,180,0.0,12.0,13,55,25,2,1.00,1.00,22.736446
15,Corn Chex,R,C,110,2,0,280,0.0,22.0,3,25,25,1,1.00,1.00,41.445019
16,Corn Flakes,K,C,100,2,0,290,1.0,21.0,2,35,25,1,1.00,1.00,45.863324

In [6]:
len(df)*len(df.columns)

1232

In [7]:
manufacturer_dict = {
  'A': 'American Home Food Products;',
  'G': 'General Mills',
  'K': 'Kelloggs',
  'N': 'Nabisco',
  'P': 'Post',
  'Q': 'Quaker Oats',
  'R': 'Ralston Purina ',
}

In [8]:
df.rename(['mfr'],manufacturer_dict)

TypeError: DataFrame.rename() takes from 1 to 2 positional arguments but 3 were given

Changing for the type column, instead of C and H, we want to use the labels of the these variables as Hot and Cold in any visualizations

In [ ]:
df.head()

In [ ]:
type_dict = {
    'C':'Cold',
    'H' : 'Hot'
}

Exploratory Data Analysis to understand the dataset and derive relationships from those data

We will begin with subplotting

In [ ]:
default_subplot_adjustment = {
    
    'left':None,
    'bottom': None,
    'right': None,
    'top': None,
    'wspace':0.4,
    'hspace':0.4
    
}

In [ ]:
def subplots_grid_visualizer(
  dataframe: pd.DataFrame,
  columns: list[str],
  visualizer: callable,
  n_cols: int = 5,
  subplot_col_width: float = 7.5,
  subplot_col_height: float = 5,
  color_palette = sns.color_palette('Paired'),
  subplots_adjustment: dict = default_subplot_adjustment,
  title: str = None,
  figsize: tuple[float, float] = None
) -> None:
  df_subplot = dataframe.copy(deep=True)
  # subplots grid configuration
  total_columns = len(columns)
  cols_to_display = n_cols
  rows_to_display = ceil(total_columns / cols_to_display)

  # subplots sizing
  if not figsize:
    figsize = (
      cols_to_display * subplot_col_width,
      rows_to_display * subplot_col_height
    )
# subplots initialization
  fig, axes = plt.subplots(rows_to_display, cols_to_display, figsize=figsize)
  if title:
    plt.suptitle(title, fontsize='xx-large')

  # set the spacing between subplots
  plt.subplots_adjust(**subplots_adjustment)

  # the actual plotting
  for index, col in enumerate(columns):
    ax = axes[
      int(index / cols_to_display),
      int(index % cols_to_display)
    ]
    visualizer(df_subplot, index, col, ax, color_palette)

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.describe().transpose()

understanding the non numeric datatypes

In [ ]:
df.select_dtypes(exclude=np.number).dtypes

now we work on seeing the distribution of the dataset

In [ ]:
TARGET_VARIABLE = 'rating' #@param {type: 'string'}
# TARGET_VARIABLE = 'fiber' #@param {type: 'string'}

In [ ]:
df['type'].unique()

In [ ]:
df['type'].count()

In [ ]:
counts = df['type'].value_counts()
counts.plot(kind='bar')


plt.xlabel('Variable')
plt.ylabel('Count')
plt.title('Value Counts of Variables in Type Column')

plt.show()

In [ ]:
type_count = df['type'].value_counts()
type_count.plot.pie(
autopct='%1.1f%%',
)

plt.title('Value Counts of Variables in Type Column')

plt.show()

In [ ]:
mfr_distribution= df['mfr'].value_counts()
mfr_distribution.plot.pie(
    autopct='%1.1f%%',
    colors=sns.color_palette('Paired'),
    fontsize=10
)
plt.title('Value distribution of Variables in Type Column')

plt.show()

In [ ]:
len(df[df['mfr'] == 'A'])

Overall data with histograms to see the distribution of all the data

In [ ]:
to_exclude = [
    'type',
    'mfr'
]
 
columns_to_plot = [col for col in df.columns if col not in to_exclude]

sns.boxplot(data=df[columns_to_plot], orient='h', palette='Set2')

plt.title('Box plot for all continuous variables in the dataset')

plt.show()

In [ ]:
plt.figure(figsize=(15,10))
_ = sns.heatmap(
df.corr().abs(),
annot=True,
fmt='.2g',
cmap='Blues'
)

In [ ]:
plt.hist(df['mfr'], bins=5, edgecolor='yellow')
plt.xlabel('mfr')
plt.ylabel('Frequency')
plt.title('Histogram of rating distribution')
plt.show()

dependency on the dependant variable

In [ ]:
correlation_columns = df.select_dtypes(include=np.number).columns
correlation_columns_to_ignore = [
    'name',
    TARGET_VARIABLE
]

correlation_columns_to_plot = [col for col in correlation_columns if col not in correlation_columns_to_ignore]
sns.set_theme(style='white')
def correlation_visualizer(df_subplot, index, col, ax, color_palette)-> None:
    temp_correlation_plot = sns.histplot(
    data=df_subplot,
    x=col,
    y=TARGET_VARIABLE,
    ax=ax,
    palette=color_palette,
    )
    
    subplots_grid_visualizer(
    Title = 'oVERALL CEREALS DATASET CORRELATION',
    dataframe = df,
    columns = correlation_columns_to_plot,
    n_cols=6, visualizer = correlation_visualizer,
    
    subplots_adjustment={
    'top': 0.9,
    'bottom': None,
    'wspace': 0.2,
    'hspace': 0.2,
  }
)

In [ ]:
def subplots_grid_visualizer(
  dataframe: df,
  columns: list[str],
  visualizer: callable,
  n_cols: int = 5,
  subplot_col_width: float = 7.5,
  subplot_col_height: float = 5,
  color_palette = sns.color_palette('Paired'),
  subplots_adjustment: dict = default_subplot_adjustment,
  title: str = None,
  figsize: tuple[float, float] = None
) -> None:
  df_subplot = dataframe.copy(deep=True)
  # subplots grid configuration
  total_columns = len(columns)
  cols_to_display = n_cols
  rows_to_display = cell(total_columns / cols_to_display)

  # subplots sizing
  if not figsize:
    figsize = (
      cols_to_display * subplot_col_width,
      rows_to_display * subplot_col_height
    )

  # subplots initialization
  fig, axes = plt.subplots(rows_to_display, cols_to_display, figsize=figsize)
  if title:
    plt.suptitle(title, fontsize='xx-large')

  # set the spacing between subplots
  plt.subplots_adjust(**subplots_adjustment)

  # the actual plotting
  for index, col in enumerate(columns):
    ax = axes[
      int(index / cols_to_display),
      int(index % cols_to_display)
    ]
    visualizer(df_subplot, index, col, ax, color_palette)

In [ ]:
columns_to_plot = [col for col in df.select_dtypes(include=np.number).columns if col not in [ TARGET_VARIABLE ] ]

sns.set_theme(style='white')
subplots_grid_visualizer(
  dataframe=df,
  columns=columns_to_plot,
  n_cols=4,
  visualizer=lambda df_subplot, index, col, ax, color_palette: (
    sns.histplot(data=df_subplot, ax=ax, x=col)
  ),
  subplot_col_width = 7.5,
  subplot_col_height = 5,
  subplots_adjustment={
    'wspace': 0.2,
    'hspace': 0.2,
  }
)

In [ ]:
df.head(77)

In [ ]:
sort_temp_df = df.copy()
sort_temp_df = sort_temp_df.sort_values(by=['rating'], ignore_index=True)

In [ ]:
sns.set_theme(style="ticks")

In [ ]:
plt.figure(figsize=(10, 5))

plt.scatter(x=sort_temp_df.rating.index, y=sort_temp_df.rating)

_ = plt.xlabel('Index')
_ = plt.ylabel('Rating')

In [ ]:
plt.figure(figsize=(10, 5))

# the less steps the more detailed
steps = 10
# steps = 2

# the stepped dataframe jumping by n intervals
stepped_sort_temp_df = sort_temp_df[::steps]
plt.plot(stepped_sort_temp_df.rating.index, stepped_sort_temp_df.rating)

_ = plt.xlabel('Index')
_ = plt.ylabel('Rating')

In [ ]:
plt.figure(figsize=(10, 5))

# the less steps the more detailed
steps = 2
# steps = 

# the stepped dataframe jumping by n intervals
stepped_sort_temp_df = sort_temp_df[::steps]
plt.plot(stepped_sort_temp_df.rating.index, stepped_sort_temp_df.rating)

_ = plt.xlabel('Index')
_ = plt.ylabel('Rating')

# data analysis

In [ ]:
df_clean = df.copy(deep=True)

In [ ]:
df_clean = df_clean[df_clean['carbo'] >=0.0]
df_clean = df_clean[df_clean['sugars'] >=0.0]
df_clean = df_clean[df_clean['potass'] >=0.0]

In [ ]:
df_clean['mfr'] = df_clean['mfr'].apply(lambda x: manufacturer_dict[x])

In [ ]:
df_clean.head()

In [ ]:
df.head()

In [ ]:
df_clean['type'] = df_clean['type'].apply(lambda x: type_dict[x])

In [ ]:
df_clean.head()

In [ ]:
if(df['sugars']<=0.0).any():
    print (df['sugars'])

In [ ]:
if (df_clean['sugars']<=0).any():
    print(df_clean['sugars'].count())

In [ ]:
df_clean['potass'].count()

In [ ]:
df_clean.describe()

In [ ]:
df_clean

In [ ]:
df_mfr =df_clean.copy(deep=True)

In [ ]:
df_mfr =df_mfr[df_mfr['sugars']>=0]

In [ ]:
sns.set_style('whitegrid')
fig, axes = plt.subplots(1,2, figsize=(30,10))
plt.suptitle('mfr and sugar correlated to rating', fontsize = 'xx-large',)
_ = sns.boxplot( data=df_mfr, x='mfr', y='sugars', ax=axes[0], showfliers=False, )
axes[0].set_title( 'Manufacturer and Sugars', fontsize='x-large', )
axes[0].set_xlabel('Manufacturer')
axes[0].set_ylabel('Sugars')


# Manufacturer and Rating
_ = sns.boxplot( data=df_mfr, x='mfr', y=TARGET_VARIABLE, ax=axes[1], showfliers=False, )
axes[1].set_title( 'Manufacturer and Rating', fontsize='x-large', )
axes[1].set_xlabel('Manufacturer')
_ = axes[1].set_ylabel('Rating')

In [ ]:
df_clean.columns

In [ ]:
nutritional_columns =[
    'protein',
    'fat',
    'sodium',
    'fiber',
    'carbo',
    'sugars',
    'potass',
    'vitamins',
    'protein',
    
]

In [ ]:

nutritional_columns = [
  'sugars',
  'fiber',
  'carbo',
  'sodium',
  'potass',
  'weight',
  'protein',
  'vitamins',
  'fat',
]

def nutritional_attribute_visualizer(df_subplot, index, col, ax, color_palette) -> None:
  _= sns.boxplot(
    data=df_subplot,
    x='calories',
    y=col,
    ax=ax,
     )
  ax.set_title(col.title(), fontsize='x-large')

sns.set_theme(style='white')
subplots_grid_visualizer(
  title='How other nutritional attributes relate to calories, a boxplot comparison',
  dataframe=df_clean,
  columns=nutritional_columns,
  n_cols=5,
  subplot_col_width = 10,
  subplot_col_height = 7.5,
  visualizer=nutritional_attribute_visualizer,
  subplots_adjustment={
    'top': 0.95,
    'bottom': None,
    'wspace': 0.2,
    'hspace': 0.2,
  }
)

In [ ]:
sum(df['weight']<0)

In [ ]:
len(df)

In [ ]:
df.columns

In [ ]:
sum((df['potass'] && df['carbo'])<0)

In [ ]:
column1='df['potass']'
column2='df['sugars']'
for index, row in df.iterrows():
    # check if both values in the current row and columns are negative
    if row[column1] < 0 and row[column2] < 0:
        sum()
    else:
        print("At least one value in row", index, "is not negative.")

In [ ]:
df_new = df_clean[ df_clean['carbo'] >= 0.0 ]

In [ ]:
len(df_new)

In [ ]:
df_new = df[ df['carbo'] >= 0.0 ]

In [ ]:
len(df_new)

In [ ]:
df_branew=df_new[df_new['potass']>=0.0]

In [ ]:
len(df_branew)

In [ ]:
(df_branew['sugars']<0).sum()

In [ ]:
df

In [ ]:
from

In [ ]:
from scipy.stats import f_oneway
from scipy.stats import ttest_ind

In [ ]:
correlation = df['rating'].corr(df['sugars'])

In [ ]:
print('correlation:', correlation)

In [ ]:
df_final = df.copy(deep=True)

# CLEANING THE DATASET

In [ ]:
df_final=df_final.drop(columns=[
    'type',
])

In [ ]:
len(df_final)

remove the abnormal values in sugar, potass and carbo that are below 0

In [ ]:
df_final=df_final[df_final['carbo'] >=0.0]
df_final=df_final[df_final['potass'] >=0.0]
df_final=df_final[df_final['sugars'] >=0.0]

In [ ]:
len(df_final)

preprocessing our dataset

In [ ]:
df_final['mfr'].unique()

In [ ]:
df_final['mfr'] = pd.factorize(df_final['mfr'])[0]

In [ ]:
df_final['name'].unique()

In [ ]:
pd.factorize(df_final['name'])[0]

In [ ]:
from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler, StandardScaler, RobustScaler

In [ ]:
scaled_dataframes = []

In [ ]:
scalers = [
    ('MinMaxScaler', MinMaxScaler()),
    ('MaxAbsScaler', MaxAbsScaler()),
    ('StandardScaler', StandardScaler()),
    ('RobustScaler', RobustScaler()),
]

In [ ]:
len(df)

In [ ]:
df_cleaned = df.copy(deep=True)
df_cleaned = df_cleaned[ df_cleaned['carbo'] >= 0.0 ]
df_cleaned = df_cleaned[ df_cleaned['sugars'] >= 0.0 ]
df_cleaned = df_cleaned[ df_cleaned['potass'] >= 0.0 ]

In [ ]:
len(df_cleaned)

In [ ]:
df_cleaned.columns

In [ ]:
len(df_clean.columns)

# Data Normalization

In [9]:
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler, MaxAbsScaler

In [10]:
scalers = [
    MinMaxScaler(),
    MaxAbsScaler(),
    StandardScaler(), 
    RobustScaler()]
scaled_dataframes = []

In [11]:
df_clean.columns

NameError: name 'df_clean' is not defined

In [12]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler

methods = [StandardScaler(), MinMaxScaler()]
normalized_datasets = []
for method in methods:
    normalized_dataset = method.fit_transform(df_clean)
    normalized_datasets.append((type(method).__name__, normalized_dataset))

NameError: name 'df_clean' is not defined

In [13]:
df

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [14]:
df=pd.read_csv('cereals.csv')

In [15]:
df

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [23]:
df.drop(columns=['type'])

,name,mfr,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,0,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,1,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,2,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,2,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
5,Apple Cinnamon Cheerios,3,110,2,2,180,1.5,10.5,10,70,25,1,1.0,0.75,29.509541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,3,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,3,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,4,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,3,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,3,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [17]:
len(df)

77

In [18]:
df = df[ df['carbo'] >= 0.0 ]
df = df[ df['sugars'] >= 0.0 ]
df = df[ df['potass'] >= 0.0 ]

In [ ]:
len(df)

In [19]:
df['mfr'] = pd.factorize(df['mfr'])[0]

In [20]:
pd.factorize(df['name'])[0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73])

In [21]:
import nltk
nltk.download('punkt')

df.apply(lambda row: nltk.word_tokenize(row['name']), axis=1)

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/joelsabiti/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

0                     [100, %, Bran]
1            [100, %, Natural, Bran]
2                         [All-Bran]
3     [All-Bran, with, Extra, Fiber]
5        [Apple, Cinnamon, Cheerios]
                   ...
72                         [Triples]
73                            [Trix]
74                     [Wheat, Chex]
75                        [Wheaties]
76           [Wheaties, Honey, Gold]
Length: 74, dtype: object

In [24]:
df

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,0,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,1,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,2,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,2,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
5,Apple Cinnamon Cheerios,3,C,110,2,2,180,1.5,10.5,10,70,25,1,1.0,0.75,29.509541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,3,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,3,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,4,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,3,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,3,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [25]:
from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler, StandardScaler, RobustScaler

In [26]:
scaled_dataframes = []

In [37]:
scalers = [
  ('MinMaxScaler', MinMaxScaler()),
  ('MaxAbsScaler', MaxAbsScaler()),
  ('StandardScaler', StandardScaler()),
  ('RobustScaler', RobustScaler()),
]

In [38]:
columns_to_standardize = [(col for columns in df.columns if(dfcolumns != 'name'))]

In [40]:
for scaler in scalers:
    scaler.fit_transform(columns_to_standardize)

AttributeError: 'tuple' object has no attribute 'fit_transform'